### ISSUE TITLE
Inconsistency in report generated when running in single vs multiple region

### ISSUE THREAD

**Issue by lhtan-dev** [aws-samples/service-screener#38]
**Describe the bug**
The generated report does not shows the same insights when run on a single region vs multiple region. 

**To Reproduce**
1. Run service screener in region a.
2. Run service screener in region a and b, 

**Expected behavior**
The generated report from step 2 should show equal or more criticality.

**Screenshots**
Single region report
![Screenshot 2023-03-23 at 16 12 38](https://user-images.githubusercontent.com/17727792/227142131-2f073b02-4483-49c8-8718-6e7b9128b7fa.png)

Multiple region report
![Screenshot 2023-03-23 at 16 12 54](https://user-images.githubusercontent.com/17727792/227142193-8df84fa8-097b-4871-8759-84b5c78f676a.png)

**AWS CloudShell (please complete the following information):**
 - Region : ap-southeast-1
 - PHP version : 8.0.27
 - AWS SDK version : CLI 2.11.2
 - Browser : chrome

**Comment by kuettai** [comment]
Hi @lhtan-dev , possible to look for error.log or error.txt within the HTML folder for "multiple region report" and share with us here?

**Comment by kuettai** [comment]
Fixed by latest commit.
