### ISSUE TITLE
SGSensitivePortOpenToAll title typo and consoleLastAccess365 title is not tally with description

### ISSUE THREAD

**Issue by cykhoo0108** [aws-samples/service-screener#4]
Descirption:
SGSEnsitivePortOpenToAll having typo, correct code should be SGSensitivePortOpenToAll.
Description of consoleLastAccess365 is mentioned 360 day instead of 365.

To Reproduce:
1. Generate report using service-screener
2. The result will display based on the description

**Comment by cykhoo0108** [comment]
Submitted the pull request for this issue

**Comment by kuettai** [comment]
Fixed by reporter with this [pull request #5 ](https://github.com/aws-samples/service-screener/pull/5)
