### ISSUE TITLE
Get PHP Fatal Error When Generate Report in HongKong Region

### ISSUE THREAD

**Issue by cykhoo0108** [aws-samples/service-screener#6]
Description:
Get PHP Error while generate report in HongKong region, looks like the issue cause my ComputOptimizer API calling

To Reproduce:
1. Create EC2 in HongKong region
2. Execute Service Screener to generate report

Expected Behavior:
Get PHP Fatal Error for EC2 part

Screenshots:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/79309705/158047009-3a16b87b-0a48-4112-b930-e0b372d12432.png)

**Comment by cykhoo0108** [comment]
Checking on this issue

**Comment by kuettai** [comment]
> Checking on this issue

Any update?

**Comment by kuettai** [comment]
Fixed by #14
